{
 "steps": [
  { 
   "name": "gcr.io/cloud-builders/gcloud",
   "args": [
    "functions", "deploy", "hello_world_test",
    "--source", "https://source.developers.google.com/projects/singja-lab-01/repos/github_singja_singja", "--region=us-central1", "--runtime=python37", "--trigger-http", "--memory=256M", "--timeout=60", "--region=us-central1", "--project=singja-lab-01",
    ]
   },
 ],
}
