steps:

# step 0
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
#  env:
#  - 'TAG_NAME=$TAG_NAME' 
  args: 
  - '-c'
  - |
    echo $TAG_NAME
    echo version-{sourceref}

# step 1
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo $SHORT_SHA

# step 2
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo $(git tag -l --points-at HEAD)

# step 3
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo $(git tag -l --points-at $SHORT_SHA)

# step 4
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo $(git show -s --format='%ae' $SHORT_SHA | sed 's/@.*//')
    
